---
- name: show top 5 cpu crocesses 
  hosts: all
  become: true 
  tasks:
    - name: top 5 cpu 
      shell: ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%cpu | head -n 6 
      register: top_cpu_processes
    - name: print top 5 cpu 
      debug:
        var: top_cpu_processes.stdout_lines 
